import type { Patient } from "@/components/patient-card";

export const mockPatients: Patient[] = [
  {
    id: "P001",
    fullName: "Sarah Johnson",
    gender: "Female",
    age: 34,
    primaryCondition: "Hypertension",
    lastAppointment: "Jan 8, 2026",
    status: "Active",
  },
  {
    id: "P002",
    fullName: "Michael Chen",
    gender: "Male",
    age: 67,
    primaryCondition: "Type 2 Diabetes",
    lastAppointment: "Jan 5, 2026",
    status: "Critical",
  },
  {
    id: "P003",
    fullName: "Emily Rodriguez",
    gender: "Female",
    age: 28,
    primaryCondition: "Asthma",
    lastAppointment: "Dec 28, 2025",
    status: "Active",
  },
  {
    id: "P004",
    fullName: "David Thompson",
    gender: "Male",
    age: 45,
    primaryCondition: "Chronic Back Pain",
    lastAppointment: "Dec 15, 2025",
    status: "Inactive",
  },
  {
    id: "P005",
    fullName: "Lisa Wang",
    gender: "Female",
    age: 52,
    primaryCondition: "Migraine",
    lastAppointment: "Jan 10, 2026",
    status: "Active",
  },
  {
    id: "P006",
    fullName: "Robert Martinez",
    gender: "Male",
    age: 73,
    primaryCondition: "Heart Disease",
    lastAppointment: "Jan 3, 2026",
    status: "Critical",
  },
  {
    id: "P007",
    fullName: "Jennifer Brown",
    gender: "Female",
    age: 29,
    primaryCondition: "Anxiety Disorder",
    lastAppointment: "Jan 7, 2026",
    status: "Active",
  },
  {
    id: "P008",
    fullName: "James Wilson",
    gender: "Male",
    age: 41,
    primaryCondition: "Allergies",
    lastAppointment: "Dec 20, 2025",
    status: "Active",
  },
  {
    id: "P009",
    fullName: "Maria Garcia",
    gender: "Female",
    age: 38,
    primaryCondition: "Arthritis",
    lastAppointment: "Nov 25, 2025",
    status: "Inactive",
  },
  {
    id: "P010",
    fullName: "Thomas Anderson",
    gender: "Male",
    age: 56,
    primaryCondition: "High Cholesterol",
    lastAppointment: "Jan 9, 2026",
    status: "Active",
  },
  {
    id: "P011",
    fullName: "Amanda Davis",
    gender: "Female",
    age: 22,
    primaryCondition: "Depression",
    lastAppointment: "Jan 6, 2026",
    status: "Active",
  },
  {
    id: "P012",
    fullName: "Christopher Lee",
    gender: "Male",
    age: 61,
    primaryCondition: "COPD",
    lastAppointment: "Dec 30, 2025",
    status: "Critical",
  },
  {
    id: "P013",
    fullName: "Rachel Green",
    gender: "Female",
    age: 35,
    primaryCondition: "Thyroid Disorder",
    lastAppointment: "Jan 4, 2026",
    status: "Active",
  },
  {
    id: "P014",
    fullName: "Kevin Taylor",
    gender: "Male",
    age: 48,
    primaryCondition: "Sleep Apnea",
    lastAppointment: "Dec 18, 2025",
    status: "Active",
  },
  {
    id: "P015",
    fullName: "Nicole White",
    gender: "Female",
    age: 31,
    primaryCondition: "Fibromyalgia",
    lastAppointment: "Jan 2, 2026",
    status: "Active",
  },
];
